services:
  supercache.filesystem.finder:
    class: noFlash\SupercacheBundle\Filesystem\Finder
    arguments: [%supercache.cache_dir%, @logger]

  supercache.cache_manager:
    class: noFlash\SupercacheBundle\Cache\CacheManager
    arguments: [@supercache.filesystem.finder, %supercache.cache_dir%]

  supercache.listeners.kernel:
    class: noFlash\SupercacheBundle\Listeners\KernelListener
    arguments: [@supercache.cache.request_handler, @supercache.cache.response_handler]
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onRequest, priority: 2147483647 }
      - { name: kernel.event_listener, event: kernel.response, method: onResponse, priority: -2147483647 }

  supercache.cache.request_handler:
    class: noFlash\SupercacheBundle\Cache\RequestHandler
    arguments: [@supercache.cache_manager, @service_container]

  supercache.cache.response_handler:
    class: noFlash\SupercacheBundle\Cache\ResponseHandler
    arguments: [@supercache.cache_manager, @service_container]

  supercache.command.cache_clearer:
    class: noFlash\SupercacheBundle\Command\CacheClearer
    arguments: [@supercache.cache_manager]
    tags:
      - { name: kernel.cache_clearer }

  supercache.utils.htaccess_generator:
    class: noFlash\SupercacheBundle\Utils\HtaccessGenerator
    arguments: [@supercache.filesystem.finder]
