language: php

sudo: false

git:
    depth: 1

cache:
    directories:
        - $HOME/.composer/cache/files

php:
    - '7.1'
    - '7.2'
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

env:
    matrix:
        - DEPENDENCIES="high"
        - DEPENDENCIES="low"
    global:
        - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-progress --no-suggest --prefer-dist"

before_install:
    - composer self-update

install:
    - if [[ "$DEPENDENCIES" = 'high' ]]; then travis_retry composer update $DEFAULT_COMPOSER_FLAGS; fi
    - if [[ "$DEPENDENCIES" = 'low' ]]; then travis_retry composer update $DEFAULT_COMPOSER_FLAGS --prefer-lowest; fi

script:
    - vendor/bin/php-cs-fixer fix -v --diff --dry-run
    - vendor/bin/phpunit

notifications:
    email: false
